# Generated by Django 4.0.3 on 2022-03-12 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
    ]
