# Generated by Django 4.0.3 on 2022-03-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_model', '0002_alter_company_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo_img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
