# Generated by Django 4.0.3 on 2022-03-12 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_model', '0003_alter_company_logo_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='created_at',
        ),
    ]
