# Generated by Django 4.0.3 on 2022-03-12 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_model', '0004_remove_company_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=255)),
                ('products', models.TextField()),
                ('service_area', models.TextField()),
                ('price_per_km', models.CharField(max_length=255)),
                ('min_distance', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_model.company')),
            ],
        ),
    ]
