# Generated by Django 4.0.3 on 2022-03-12 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery_service_model', '0002_alter_deliveryservice_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_address', models.TextField()),
                ('to_address', models.TextField()),
                ('date', models.CharField(max_length=255)),
                ('is_done', models.BooleanField(default=False)),
                ('in_progress', models.BooleanField(default=False)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_book', to='delivery_service_model.deliveryservice')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_book', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
