# Generated by Django 4.0.3 on 2022-03-12 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('packaging_service_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagingBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('date', models.CharField(max_length=255)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('packaging_service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packaging_service_model.packagingservice')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
