# Generated by Django 4.0.3 on 2022-03-12 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('packaging_service_model', '0001_initial'),
        ('packaging_book_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagingbook',
            name='is_done',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='packagingbook',
            name='packaging_service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaging_book', to='packaging_service_model.packagingservice'),
        ),
        migrations.AlterField(
            model_name='packagingbook',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaging_book', to=settings.AUTH_USER_MODEL),
        ),
    ]
