# Generated by Django 4.0.3 on 2022-03-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packaging_book_model', '0002_packagingbook_is_done_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagingbook',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
