# Generated by Django 4.0.3 on 2022-03-12 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_model', '0004_remove_company_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('price_per_kg', models.CharField(max_length=255)),
                ('max_volume', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_service', to='company_model.company')),
            ],
        ),
    ]
