# Generated by Django 4.0.3 on 2022-03-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_service_model', '0002_exportservice_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportservice',
            name='address',
            field=models.TextField(),
        ),
    ]
