# Generated by Django 4.0.3 on 2022-03-12 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_model', '0002_alter_company_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_area', models.TextField()),
                ('product_type', models.CharField(choices=[('Meva', 'Meva'), ('Poliz', 'Poliz'), ('Sabzavot', 'Sabzavot'), ('Dukkakli', 'Dukkakli'), ('Ziravor', 'Ziravor')], default='Meva', max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('min_amount', models.CharField(max_length=255)),
                ('package_type', models.CharField(max_length=255)),
                ('price_per_kg', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_model.company')),
            ],
        ),
    ]
