# Generated by Django 4.0.3 on 2022-03-12 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_model', '0004_remove_company_created_at'),
        ('packaging_service_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagingservice',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaging_service', to='company_model.company'),
        ),
    ]
