# Generated by Django 4.0.3 on 2022-03-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packaging_service_model', '0002_alter_packagingservice_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagingservice',
            name='example_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
